### ISSUE TITLE
Doesn't compile

### ISSUE THREAD

**Issue by Zireael07** [sunsided/stroke-width-transform-rs#4]
error[E0597]: `desc_set` does not live long enough
    --> /home/kasia/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-core-0.9.0/src/device/mod.rs:1801:26
     |
1801 |                     set: desc_set.raw_mut(),
     |                          ^^^^^^^^^^^^^^^^^^ borrowed value does not live long enough
...
1822 |     }
     |     -
     |     |
     |     `desc_set` dropped here while still borrowed
     |     borrow might be used here, when `write_map` is dropped and runs the `Drop` code for type `BTreeMap`
     |
     = note: values in a scope are dropped in the opposite order they are defined

error: could not compile `wgpu-core` due to previous error

rustc 1.65.0 (897e37553 2022-11-02)

**Comment by sunsided** [comment]
Hey. I just upgraded the dependencies, could be that dependabot borked it up and I didn't check after. It compiles now (Rust 1.68.2).

**Comment by Zireael07** [comment]
Hmm, maybe it's time to upgrade Rust? Because while it progresses past that, it still doesn't compile:

 Compiling clap v4.2.1
error[E0432]: unresolved imports `clap::AppSettings`, `clap::Clap`
 --> examples/swt.rs:1:12
  |
1 | use clap::{AppSettings, Clap};
  |            ^^^^^^^^^^^  ^^^^ no `Clap` in the root
  |            |
  |            no `AppSettings` in the root

error: cannot determine resolution for the derive macro `Clap`
  --> examples/swt.rs:10:10
   |
10 | #[derive(Clap)]
   |          ^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error: cannot find attribute `clap` in this scope
  --> examples/swt.rs:11:3
   |
11 | #[clap(version = "0.1", author = "Markus Mayer <widemeadows@gmail.com>")]
   |   ^^^^
   |
   = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
  --> examples/swt.rs:12:3
   |
12 | #[clap(setting = AppSettings::ColoredHelp)]
   |   ^^^^
   |
   = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
  --> examples/swt.rs:15:7
   |
15 |     #[clap(short, long)]
   |       ^^^^
   |
   = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
  --> examples/swt.rs:19:7
   |
19 |     #[clap(short, long)]
   |       ^^^^
   |
   = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot find attribute `clap` in this scope
  --> examples/swt.rs:23:7
   |
23 |     #[clap(validator(file_exists))]
   |       ^^^^
   |
   = note: `clap` is in scope, but it is a crate, not an attribute

error[E0599]: no function or associated item named `parse` found for struct `Opts` in the current scope
  --> examples/swt.rs:28:28
   |
13 | struct Opts {
   | ----------- function or associated item `parse` not found for this struct
...
28 |     let opts: Opts = Opts::parse();
   |                            ^^^^^ function or associated item not found in `Opts`
   |
   = help: items from traits can only be used if the trait is implemented and in scope
   = note: the following traits define an item `parse`, perhaps you need to implement one of them:
           candidate #1: `Parser`
           candidate #2: `TypedValueParser`
           candidate #3: `nom::internal::Parser`
           candidate #4: `nom::sequence::Tuple`
           candidate #5: `ttf_parser::parser::FromData`
           candidate #6: `ttf_parser::parser::FromSlice`
           candidate #7: `ttf_parser::ggg::lookup::LookupSubtable`
           candidate #8: `ttf_parser::ggg::layout_table::RecordListItem`

Some errors have detailed explanations: E0432, E0599.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `stroke-width-transform-rs` due to 8 previous errors

**Comment by sunsided** [comment]
Ah, no, you are absolutely right, I did not check on the example. Give me a bit, I'll look into it.

Edit: Done. :)
